name: Release Gateway

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  attestations: write
  contents: write
  issues: write
  discussions: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup GoLang
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Make binaries
        run: make binaries
        working-directory: ./gateway

      - name: Upload binaries
        uses: https://github.com/christopherHX/gitea-upload-artifact@v4
        with:
          name: bin
          path: ./gateway/bin

  gitea_release:
    needs: build
    runs-on: ubuntu-latest

    env:
      GITEA_SERVER_URL: ${{ secrets.GITEA_SERVER_URL || 'https://git.ragestudio.net' }}
      GITEA_REPOSITORY: ${{ github.repository }}
      GITEA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: https://github.com/christopherHX/gitea-download-artifact@v4
        with:
          name: bin
          path: bin

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            bin/*

          body: |
            ## New Release
            Automated build for ${{ github.ref_name }}

          prerelease: ${{ contains(github.ref_name, '-next') }}
          draft: false
          fail_on_unmatched_files: true
