name: Build Gateway

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  attestations: write
  contents: write
  issues: write
  discussions: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup GoLang
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Make binaries
        run: make binaries
        working-directory: ./gateway

      - name: Upload Linux AMD64 Binary
        uses: https://github.com/christopherHX/gitea-upload-artifact@v4
        with:
          name: ultragateway-linux-amd64
          path: ./gateway/bin/ultragateway.linux.x86_64

      - name: Upload Linux AMD64-v3 Binary
        uses: https://github.com/christopherHX/gitea-upload-artifact@v4
        with:
          name: ultragateway-linux-amd64-v3
          path: ./gateway/bin/ultragateway.linux.v3.x86_64

      - name: Upload Linux ARM64 Binary
        uses: https://github.com/christopherHX/gitea-upload-artifact@v4
        with:
          name: ultragateway-linux-arm64
          path: ./gateway/bin/ultragateway.linux.aarch64
