name: Release CLI

on:
  workflow_dispatch:
  push:
    tags:
      - "cli-v*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release to Registry
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            cli

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org/"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11

      - name: Publish to NPM via Trusted Publishing
        run: pnpm publish --no-git-checks --provenance .
