name: Documentation

on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths:
            - "docs/**"
    repository_dispatch:
        types: [docs]
    gollum:

env:
    GIT_AUTHOR_NAME: Actionbot
    GIT_AUTHOR_EMAIL: actions@github.com

jobs:
    job-sync-docs-to-wiki:
        runs-on: ubuntu-latest
        if: github.event_name != 'gollum'
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Sync docs to wiki
              uses: newrelic/wiki-sync-action@main
              with:
                  source: docs
                  destination: wiki
                  token: ${{ secrets.GITHUB_TOKEN }}
                  gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
                  gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
